#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1052':
        pose: /mocap/external_position
        tf: tf
        child_frame_id: Robot_1/base_link
        parent_frame_id: world
        
    '1054':
        pose: /mocap/object_pos_1
        tf: tf
        child_frame_id: Obstacle_1/base_link
        parent_frame_id: world

    '1055':
        pose: /mocap/object_pos_2
        tf: tf
        child_frame_id: Obstacle_1/base_link
        parent_frame_id: world
optitrack_config:
        multicast_address: 239.255.42.99
        command_port: 1510
        data_port: 1511
        enable_optitrack: true
        


